replicaCount: 1

image:
  repository: ${DOCKER_REGISTRY}
  imageName: final-challenge-grupo-118-users
  tag: "${POC_IMAGE_TAG}"  # Will be set via --set or CI/CD
  pullPolicy: IfNotPresent
  
imagePullSecrets:
  - name: final-challenge-grupo-118-users-acr-secret
    
acrCredentials:
  enabled: true
  registry: "${DOCKER_REGISTRY}"
  username: "${ACR_USERNAME}"  # Will be set via --set or CI/CD
  password: "${ACR_PASSWORD}"  # Will be set via --set or CI/CD
  
nameOverride: "final-challenge-grupo-118-users"
fullnameOverride: "final-challenge-grupo-118-users"

serviceAccount:
  create: true
  annotations: {}
  name: "final-challenge-grupo-118-users-sa"
  
service:
  port: 80
  instances:
    - name: final-challenge-grupo-118-users
      type: ClusterIP
      port: 80
      targetPort: 8080
      portName: http
      
internalIngress:
  enabled: true
  className: "nginx-internal-static"
  path: /users-api(/|$)(.*)
  pathType: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: []
  
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 90
  periodSeconds: 30
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 4
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 10
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

persistence:
  enabled: false

configMap:
  enabled: false
  
secret:
  enabled: true
  name: final-challenge-grupo-118-users
  annotations: {}
  data:
    #         STEPS: 2. Criação das chaves no secret, com os valores que foram mapeados dos segredos
    users-sql-connectionstring: "${ConnectionStrings__DefaultConnection}"
    users-redis-connectionstring: "${ConnectionStrings__Redis}"   
    users-security-securitykey: "${Security__SecurityKey}"
    users-security-jwtkey: "${Security__JwtKey}"
    users-security-jwtissuer: "${Security__JwtIssuer}"
    users-security-jwtaudience: "${Security__JwtAudience}"
    users-security-jwttexpiration: "${Security__JwtExpirationMinutes}"
    otlp-url: "${OpenTelemetry__Url}"

  #         STEPS: 3. Mapear as chaves dos segredos para variaveis de ambientes, no formato que o asp.net reconhece para sobrescrever as configs do json
  envVars:
    - name: ConnectionStrings__DefaultConnection
      secretKey: users-sql-connectionstring
    - name: ConnectionStrings__Redis
      secretKey: users-redis-connectionstring
    - name: Security__SecurityKey
      secretKey: users-security-securitykey
    - name: Security__JwtKey
      secretKey: users-security-jwtkey
    - name: Security__JwtIssuer
      secretKey: users-security-jwtissuer
    - name: Security__JwtAudience
      secretKey: users-security-jwtaudience
    - name: Security__JwtExpirationMinutes
      secretKey: users-security-jwttexpiration
    - name: OpenTelemetry__Url
      secretKey: otlp-url

nodeSelector: {}

tolerations: []

affinity: {} 