name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true
      helm_chart_version:
        description: 'Helm chart version to deploy'
        required: true
      helm_chart_name:
        description: 'Field to insert the Helm Chart Name'
        required: true
        default: "grupo118fasefinal"
      helm_release_name:
        description: 'Field to define the release name'
        required: true
        default: 'final-challenge-grupo-118-users'

jobs:
  deploy:
    uses: Grupo-118-Desafio-Final/final-challenge-grupo-118-template-pipeline/.github/workflows/dotnet-cd-template.yml@main
    secrets: inherit
    with:
      helm_chart_version: ${{ github.event.inputs.helm_chart_version }}
      helm_chart_name: ${{ github.event.inputs.helm_chart_name }}
      helm_values_file: "helm/values-production.yaml"
      helm_release_name: ${{ github.event.inputs.helm_release_name }}
      #         STEPS: 1. Mapear os segredos para as variaveis do helm, do jeito que api espera
      secrets_mapping: |
        {
            "DOCKER_REGISTRY": "DOCKER_REGISTRY",
            "ACR_USERNAME": "ACR_USERNAME",
            "ACR_PASSWORD": "ACR_PASSWORD",
            "ConnectionStrings__DefaultConnection": "APPLICATION_SQLSERVER_CONNECTIONSTRING",
            "ConnectionStrings__Redis": "APPLICATION_REDIS_CONNECTIONSTRING",
            "Security__SecurityKey":"APPLICATION_SECURITY_SECURITYKEY",
            "Security__JwtKey":"APPLICATION_SECURITY_JWTKEY",
            "Security__JwtIssuer":"APPLICATION_SECURITY_JWTISSUER",
            "Security__JwtAudience":"APPLICATION_SECURITY_JTWAUDIENCE",
            "Security__JwtExpirationMinutes":"APPLICATION_SECURITY_JWTEXPIRATION",
            "OpenTelemetry__Url": "GRAFANA_OTLP_URL"
        }
      variables_mapping: |
        {
            "POC_IMAGE_TAG": "${{ github.event.inputs.image_tag }}"
        }